### ISSUE TITLE
Fastboot compatibility

### ISSUE THREAD

**Issue by christophermlne** [adopted-ember-addons/ember-pikaday#109]
An Ember project will not build successfully if this addon is present in package.json

The Fastboot addon author guide has steps listed to ensure addon is compatible with Fastboot:
http://www.ember-fastboot.com/docs/addon-author-guide

**Comment by josemarluedke** [comment]
Yes, would be awesome to get this addon working with fastboot.

**Comment by duizendnegen** [comment]
At the moment `ember-pikaday` is quite coupled with `Pikaday`, ideally we'd tease out these two a bit more so that e.g. interaction is still possible with Fastboot, just not with the date picker actually opening.

Steps required:
[ ] Make list of non-fastboot compatible calls
[ ] Wrap date interaction in own abstraction

Happy to receive your input on both points. I currently do not work with fastboot, so might not touch this myself for the coming time.

**Comment by duizendnegen** [comment]
The main use case is solved - thanks @josemarluedke.
As I wrote elsewhere, I'm keeping this issue open, as I think there may be value in abstracting away date interaction to enable usage without Pikaday.js, e.g. #90.

**Comment by alexlafroscia** [comment]
@duizendnegen do you still think it's worth keeping this issue open?

I, for one, don't foresee removing `Pikaday.js` and the addon seems to strip the files correctly for FastBoot.

Let's discuss and re-open if there's actually more to do here.
