### ISSUE TITLE
Initializer fails to load a locale when using with ember-intl

### ISSUE THREAD

**Issue by belgoros** [adopted-ember-addons/ember-pikaday#215]
When migrating from [ember-i18n](https://github.com/jamesarosen/ember-i18n) to [ember-intl](https://github.com/ember-intl/ember-intl), the previous `setup-pikaday-i18n.js` initializer defined as suggested in [Localization](https://github.com/adopted-ember-addons/ember-pikaday#localization) section of README does not the locale set in `beforeModel` hook of `application.js` route:
```
#routes/application.js

beforeModel() {
    let locale = this.figureOutLocale();
    this.intl.setLocale(locale);
    moment.locale(locale);
    console.log('locale: ' + locale);
    console.log('moment locale: ' + moment.locale());
    return this._loadCurrentUser();
  },
...
figureOutLocale() {
    let locale = this.calculateLocale(this.intl.get('locales'));
    return locale;
  },

  calculateLocale(locales) {
    const language = navigator.languages[0] || navigator.language || navigator.userLanguage;

    return  locales.includes(language.toLowerCase()) ? language : 'en-US';
  }
```
Here is how `setup-pikaday-i18n.js` is defined:

```
#initializers/setup-pikaday-i18n.js

export default {
  name: 'setup-pikaday-i18n',
  initialize: function(application) {
    console.log('in initializer locale: ' + moment.locale())
    var i18n = Ember.Object.extend({
      months: moment.localeData()._months,
      weekdays: moment.localeData()._weekdays,
      weekdaysShort: moment.localeData()._weekdaysShort
    });    

    application.register('pikaday-i18n:main', i18n, { singleton: true });
    application.inject('component:pikaday-input', 'i18n', 'pikaday-i18n:main');
  }
};
```
When loading the application, the console displays:
```
in initializer locale: en
locale: fr-FR
moment locale: fr
```
As you see, the initializers still uses the default locale and pikaday-input defines as follows in a template:
```
{{pikaday-input
      value=holiday.date
      class="form-control"
      onSelection=(action (mut holiday.date))
      readonly="readonly"
      format="DD/MM/YYYY"
      useUTC=true
    }}
```
displays months and weekdays in English instead of teh locales set up in `application` route.
Any ideas on how to fix that?
By the way, my previous [issue](https://github.com/adopted-ember-addons/ember-pikaday/issues/187) used the same initializer defined in `instance-initializers` directory to make it work. Actually none of these solutions works.

Thank you.

**Comment by alexlafroscia** [comment]
Hey @belgoros. Let me to try to explain back to you the situation, so I can make sure I understand it. What I'm getting from the code examples and explanation is that

- Pikaday gets the localization data from an initializer. This locale is `en`
- Some application logic uses the `beforeModel` hook of your Application route to look up the correct locale based on some logic and set it on the `intl` service and `moment`

It makes sense to me, in that case, that Pikaday is using the wrong locale, because the `fr-FR` localization info that you determine based on your logic happens _after_ PIkaday has already been configured with the values from Moment, which likely defaults to `en`.

I would suggest moving the `figureOutLocale` logic into an initializer as well, either at the top of your `setup-pikaday-i18n.js` one or in its own initializer that is configured to be run before the Pikaday one. I think the root of this issue is the timing between when you configure the non-default value and when Pikaday is configured. Pikaday is just getting configured before your custom logic is run.

For the meantime I'm going to close this issue, because I don't think it's actually a bug on `ember-pikaday`. Feel free to continue the conversation here, though, if I can help any more, and I'm happy to re-open if there is a bug here!

**Comment by belgoros** [comment]
Alex, thank you for the feedback. Another solution that worked for me would be to create a component as follows:
```
#components/pikaday-input.js

import PikadayInput from 'ember-pikaday/components/pikaday-input';
import moment from 'moment';

export default PikadayInput.extend({
  init() {
    this._super(...arguments);
    this.i18n = {
      months: moment.localeData()._months,
      weekdays: moment.localeData()._weekdays,
      weekdaysShort: moment.localeData()._weekdaysShort
    };
  }
});
```
to fix that. Hope this helps.

**Comment by alexlafroscia** [comment]
That's a nice approach, too!

I think I even like that better, @belgoros, since it avoids having an initializer that modifies the global helper's behavior. IMO it's much easier to hunt down the source of behavior when you keep it all in a component like this.

**Comment by belgoros** [comment]
@alexlafroscia Thanks to [Robert Jackson](https://discuss.emberjs.com/t/how-to-start-with-testing/16140/9)who proposed this great idea and helped me to fix that 👍

**Comment by ggalli** [comment]
The component solution worked well, but how can I do the same with a pikaday-inputless? can someone help me with an example?
